name: Discord Release Notifier

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "🚀 Nuova Release Disponibile!"
          description: |
            Versione: **${{ github.event.release.tag_name }}**
            Note di rilascio: ${{ github.event.release.html_url }}
          color: 0x28a745
